import React from 'react'
import Navbar_header from '../Navbar';
import Gallery from './Gallery';
import Footer from '../Footer';

export default function HomePage() {
    

    return (
        <>
            <Navbar_header />
            <div className="text-center">
                <Gallery />
              
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />

                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />
                <Gallery />


            </div>
            <Footer />
        </>

    )
}


